### ISSUE TITLE
CREAR MODELO DE ENTIDADES

### ISSUE THREAD

**Issue by daniguacu** [daniguacu/PROYECTOESTACIONES#9]
https://app.creately.com/diagram/a1z4opYskFK/edit

**Comment by hectoracevedogit1** [comment]
Se crea modelo de entidades con las clases del proyecto

https://app.creately.com/diagram/a1z4opYskFK/edit

**Comment by edgarcabc** [comment]
hola.

Me escribes si debo hacer algo en el proyecto. aun no tengo mi equipo
celular. si usas skype mi usuario es edgarcabc
